-- 1) todos 테이블 생성
create table todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_complete boolean default false,
  inserted_at timestamp with time zone default now()
);

-- 2) RLS(Row Level Security) 활성화
alter table todos enable row level security;

-- 3) 누구나(익명 키 포함) 읽고 쓸 수 있도록 정책 추가
--    ⚠️ 로그인 기능이 없는 개인용/데모 앱 기준입니다.
--    여러 사용자가 함께 쓰는 서비스라면 auth.uid() 기반으로 정책을 다시 작성하세요.
create policy "Allow public read access"
  on todos for select
  using (true);

create policy "Allow public insert access"
  on todos for insert
  with check (true);

create policy "Allow public update access"
  on todos for update
  using (true);

create policy "Allow public delete access"
  on todos for delete
  using (true);
